CREATE OR REPLACE TRIGGER UPDATE_CUSTOMER_INFO
AFTER INSERT ON PURCHASES
FOR EACH ROW

BEGIN
   Update CUSTOMERS
     SET VISITS_MADE = VISITS_MADE + 1, LAST_VISIT_DATE = SYSDATE
   WHERE CID = :NEW.CID;
END;
/
SHOW ERRORS