CREATE  OR REPLACE TRIGGER QOH_TRIGGER

BEFORE INSERT ON PURCHASES
FOR EACH ROW

DECLARE 
OG_QOH NUMBER;
NEGATIVE_QOH EXCEPTION;


BEGIN
   
   SELECT QOH INTO OG_QOH
   FROM PRODUCTS
   WHERE PID=:NEW.PID;

   IF (:NEW.QTY > OG_QOH) THEN 
        RAISE NEGATIVE_QOH;
   END IF;

   EXCEPTION
        WHEN NEGATIVE_QOH THEN
        RAISE_APPLICATION_ERROR (-20001, 'CANNOT COMPLETE PURCHASE: INSUFFICIENT QUANTITY IN STOCK');

END;
/
SHOW ERRORS 